name: Frontend CI/CD Pipeline

on:
  push:
    branches: [ main, develop, master, dummy ]  # 원하는 브랜치 추가
  pull_request:
    branches: [ main, develop, master, dummy ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Build React App
        env:
          CI: false
        run: |
          npm ci
          npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/portfolio_frontend:${{ github.sha }} -t $ECR_REGISTRY/portfolio_frontend:latest .
          docker push $ECR_REGISTRY/portfolio_frontend:${{ github.sha }}
          docker push $ECR_REGISTRY/portfolio_frontend:latest

      - name: Update Kubernetes manifests (ArgoCD trigger)
        uses: actions/checkout@v3
        with:
          repository: mapzine123/kgat-k8s-manifests 
          token: ${{ secrets.GH_TOKEN }}
          path: k8s-manifests

      - name: Install ArgoCD CLI
        run: |
          curl -sSL https://github.com/argoproj/argo-cd/releases/download/v2.7.5/argocd-linux-amd64 -o /usr/local/bin/argocd
          chmod +x /usr/local/bin/argocd

      - name: Update image tag in manifests
        run: |
          cd k8s-manifests
          # 절대 경로로 변경하거나, 경로 문제를 해결
          sed -i "s|image: .*portfolio_frontend:.*|image: ${{ steps.login-ecr.outputs.registry }}/portfolio_frontend:${{ github.sha }}|" frontend/portfolio_frontend.yaml
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Update image to ${{ github.sha }}"
          git push

      - name: Trigger ArgoCD sync
        run: |
          argocd app sync portfolio_frontend --auth-token ${{ secrets.ARGOCD_AUTH_TOKEN }} --server ${{ secrets.ARGOCD_SERVER }}
